### ISSUE TITLE
Use of English in Menu headers

### ISSUE THREAD

**Issue by jbrucker** [woraamy/KU-international-menu-project#23]
https://github.com/woraamy/KU-international-menu-project/blob/cf95c8a0f8743a2ae695bd734c4021c8bf4e0c95/menu.md?plain=1#L7

The column headings are incorrect use of English.  The items are not "Menus" so should not be "Menu Name", "Menu Description".

Delete the word "Menu".

**Comment by Peanutt47** [comment]
fit it
